/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123777-g53537f6cf5-20260331"
#endif /* AVUTIL_FFVERSION_H */
